databases:
  - name: phish_guard_db
    databaseName: phish_guard_db
    user: phish_learning
    region: singapore

services:
  - type: web
    name: phish_learning
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: phish_guard_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false